### ISSUE TITLE
Old quarterly histogram?

### ISSUE THREAD

**Issue by misaochan** [whym/commons-app-stats#9]
Hi @whym ,

The new quarterly histogram seems to be a bit buggy - edits aren't shown in 2017, and uploads in 2017 Q2 appears lower than I recall. Is there a reason why we switched to the new quarterly histogram? I admit to being partial to the old one which displayed data from the start of the app (in 2013 or something I think), as that gave a very good overall picture of stats. :)

**Comment by whym** [comment]
No, I didn't intend to cut off older parts of the chart. One reason I can think of is that it perhaps uses a too heavy query and the returned data might be incomplete.

it tries to retrieve all metadata of mobile contributions back since 2013 every time it runs (once a week). This was easier for me to do because I didn't have to consider how to store the retrieved data, but it's taxing to the database server. I might have to be more polite with how I use database queries.

**Comment by misaochan** [comment]
Ah okay, thanks for clarifying! :) I thought it was an intended change as it only happened after the recent changes. I wonder if there's a way for me to access the quarterly histogram the way it was a few weeks ago? It was working fine for me then, but unfortunately I hadn't saved a screenshot.

**Comment by whym** [comment]
archive.org has an old chart from August 2018: https://web.archive.org/web/20180823144015im_/http://tools.wmflabs.org/commons-app-stats/latest_quarter.svg - this is the latest one I have access to.

**Comment by whym** [comment]
I discovered that I was entirely aware of a recent change in the database layout. It looks like the revision comments we use have been migrated into another database table. https://phabricator.wikimedia.org/T166733 I will try rewriting the queries accordingly.

**Comment by misaochan** [comment]
Thanks so much for the investigations @whym . The quarterly table looks REALLY strange to me now, but I guess it's a WIP. :)

**Comment by misaochan** [comment]
Looks fantastic! Thanks :)
